# Generated by Django 5.0.6 on 2024-05-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
